/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ApiKey {
  'id' : bigint,
  'active' : boolean,
  'userId' : string,
  'name' : string,
  'createdAt' : bigint,
  'keyHash' : string,
}
export interface BacktestResult {
  'id' : bigint,
  'totalTrades' : bigint,
  'timeframe' : string,
  'userId' : string,
  'createdAt' : bigint,
  'sharpeRatio' : number,
  'totalPnl' : number,
  'winRate' : number,
  'maxDrawdown' : number,
  'symbol' : string,
  'strategyId' : bigint,
}
export interface BrokerConfig {
  'redirectUrl' : string,
  'paperMode' : boolean,
  'secret' : string,
  'webhook' : string,
  'algorithmEnabled' : boolean,
  'apiKey' : string,
  'accessToken' : string,
  'liveMode' : boolean,
  'tradingMode' : string,
}
export interface BrokerConnection {
  'broker' : string,
  'paperMode' : boolean,
  'secret' : string,
  'apiKey' : string,
  'connected' : boolean,
  'accessToken' : string,
}
export interface Candle {
  'low' : number,
  'timeframe' : string,
  'high' : number,
  'close' : number,
  'open' : number,
  'volume' : bigint,
  'timestamp' : bigint,
  'symbol' : string,
}
export interface ExtendedRiskSettings {
  'autoStopTrading' : boolean,
  'maxOpenTrades' : bigint,
  'capitalAllocation' : number,
  'maxTradeRisk' : number,
  'maxDailyLoss' : number,
}
export interface MarketplaceListing {
  'id' : bigint,
  'lifetimePrice' : number,
  'createdAt' : bigint,
  'creatorId' : string,
  'description' : string,
  'isFree' : boolean,
  'creatorName' : string,
  'sharpeRatio' : number,
  'enabled' : boolean,
  'subscribers' : bigint,
  'monthlyPrice' : number,
  'assetType' : string,
  'winRate' : number,
  'strategyName' : string,
  'maxDrawdown' : number,
}
export interface NinetwentyState {
  'line' : number,
  'entry' : number,
  'stopLoss' : number,
  'signal' : string,
}
export interface Notification {
  'id' : bigint,
  'userId' : string,
  'notificationType' : string,
  'read' : boolean,
  'message' : string,
  'emailEnabled' : boolean,
  'timestamp' : bigint,
}
export interface RiskSettings {
  'autoShutdown' : boolean,
  'maxDailyLoss' : number,
  'maxTradesPerDay' : bigint,
  'maxCapitalPerTrade' : number,
}
export interface Strategy {
  'id' : bigint,
  'algorithmFile' : string,
  'riskPercent' : number,
  'name' : string,
  'shortWindow' : bigint,
  'longWindow' : bigint,
  'positionSize' : bigint,
  'enabled' : boolean,
  'stopLossPercent' : number,
  'targetPercent' : number,
  'strategyType' : string,
}
export interface SubscriptionRecord {
  'active' : boolean,
  'subscribedAt' : bigint,
  'listingId' : bigint,
  'userId' : string,
  'plan' : string,
}
export interface Trade {
  'id' : bigint,
  'pnl' : number,
  'status' : string,
  'userId' : string,
  'mode' : string,
  'side' : string,
  'stopLoss' : number,
  'timestamp' : bigint,
  'quantity' : bigint,
  'price' : number,
  'strategyName' : string,
  'symbol' : string,
}
export interface UserProfile {
  'experienceLevel' : string,
  'country' : string,
  'followersCount' : bigint,
  'name' : string,
  'joinedAt' : bigint,
  'role' : string,
  'pendingApproval' : boolean,
  'email' : string,
  'tradingMarket' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addNotification' : ActorMethod<[string, string, string], Notification>,
  'addStrategy' : ActorMethod<
    [string, bigint, bigint, number, number, bigint, number, string, string],
    bigint
  >,
  'addTrade' : ActorMethod<
    [string, string, string, bigint, number, string],
    bigint
  >,
  'approveCreator' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearNinetwentyState' : ActorMethod<[], undefined>,
  'closeTrade' : ActorMethod<[bigint], undefined>,
  'disconnectBroker' : ActorMethod<[string], undefined>,
  'exitAllTrades' : ActorMethod<[], undefined>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'forceAddDailyCandle' : ActorMethod<
    [number, number, number, number, bigint, string, string, bigint],
    undefined
  >,
  'generateApiKey' : ActorMethod<[string], ApiKey>,
  'getActiveMarketplaceListings' : ActorMethod<[], Array<MarketplaceListing>>,
  'getAdminDashboardStats' : ActorMethod<
    [],
    {
      'activeStrategies' : bigint,
      'todayPnl' : number,
      'squareOffMode' : boolean,
      'accountBalance' : number,
      'activeTrades' : bigint,
      'totalStrategies' : bigint,
      'winRate' : number,
    }
  >,
  'getAdminStats' : ActorMethod<
    [],
    {
      'totalTrades' : bigint,
      'totalPnl' : number,
      'openTrades' : bigint,
      'totalUsers' : bigint,
    }
  >,
  'getAllTrades' : ActorMethod<[], Array<Trade>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getBrokerConfig' : ActorMethod<[], BrokerConfig>,
  'getBrokerConnections' : ActorMethod<[], Array<BrokerConnection>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCandles' : ActorMethod<[string, string, bigint], Array<Candle>>,
  'getExtendedRiskSettings' : ActorMethod<[], ExtendedRiskSettings>,
  'getMarketplaceListings' : ActorMethod<[], Array<MarketplaceListing>>,
  'getMyApiKeys' : ActorMethod<[], Array<ApiKey>>,
  'getMyBacktestResults' : ActorMethod<[], Array<BacktestResult>>,
  'getMyNotifications' : ActorMethod<[], Array<Notification>>,
  'getMyTrades' : ActorMethod<[], Array<Trade>>,
  'getNinetwentyLine' : ActorMethod<[], number>,
  'getNinetwentyState' : ActorMethod<[], NinetwentyState>,
  'getNotificationUnreadCount' : ActorMethod<[], bigint>,
  'getPendingCreators' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getPublicUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getRiskSettings' : ActorMethod<[], RiskSettings>,
  'getSquareOffMode' : ActorMethod<[], boolean>,
  'getStrategies' : ActorMethod<[], Array<Strategy>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSubscriptions' : ActorMethod<[], Array<SubscriptionRecord>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationsRead' : ActorMethod<[], undefined>,
  'modifyStopLoss' : ActorMethod<[bigint, number], undefined>,
  'rejectCreator' : ActorMethod<[Principal], undefined>,
  'revokeApiKey' : ActorMethod<[bigint], undefined>,
  'saveBacktestResult' : ActorMethod<
    [bigint, string, string, number, number, number, number, bigint],
    bigint
  >,
  'saveBrokerConfig' : ActorMethod<
    [string, string, string, string, string, boolean, boolean, string],
    undefined
  >,
  'saveBrokerConnection' : ActorMethod<
    [string, string, string, string, boolean],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveExtendedRiskSettings' : ActorMethod<
    [number, number, bigint, number, boolean],
    undefined
  >,
  'saveMarketplaceListing' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      number,
      number,
      number,
      number,
      number,
      boolean,
    ],
    bigint
  >,
  'saveRiskSettings' : ActorMethod<
    [number, bigint, number, boolean],
    undefined
  >,
  'setNinetwentyLine' : ActorMethod<[number], undefined>,
  'setNinetwentySignal' : ActorMethod<[string, number, number], undefined>,
  'setTradingMode' : ActorMethod<[string], undefined>,
  'subscribeToStrategy' : ActorMethod<[bigint, string], undefined>,
  'toggleAlgorithm' : ActorMethod<[], undefined>,
  'toggleSquareOffMode' : ActorMethod<[], undefined>,
  'toggleStrategy' : ActorMethod<[bigint], undefined>,
  'updateNotificationEmailPref' : ActorMethod<[string, boolean], undefined>,
  'updateStrategyPricing' : ActorMethod<
    [bigint, number, number, boolean],
    undefined
  >,
  'updateTrade' : ActorMethod<[bigint, string, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];