/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BacktestResult {
  'id' : bigint,
  'totalTrades' : bigint,
  'timeframe' : string,
  'userId' : string,
  'createdAt' : bigint,
  'sharpeRatio' : number,
  'totalPnl' : number,
  'winRate' : number,
  'maxDrawdown' : number,
  'symbol' : string,
  'strategyId' : bigint,
}
export interface BrokerConfig {
  'redirectUrl' : string,
  'paperMode' : boolean,
  'secret' : string,
  'webhook' : string,
  'algorithmEnabled' : boolean,
  'apiKey' : string,
  'accessToken' : string,
  'liveMode' : boolean,
  'tradingMode' : string,
}
export interface Candle {
  'low' : number,
  'timeframe' : string,
  'high' : number,
  'close' : number,
  'open' : number,
  'volume' : bigint,
  'timestamp' : bigint,
  'symbol' : string,
}
export interface RiskSettings {
  'autoShutdown' : boolean,
  'maxDailyLoss' : number,
  'maxTradesPerDay' : bigint,
  'maxCapitalPerTrade' : number,
}
export interface Strategy {
  'id' : bigint,
  'algorithmFile' : string,
  'riskPercent' : number,
  'name' : string,
  'shortWindow' : bigint,
  'longWindow' : bigint,
  'positionSize' : bigint,
  'enabled' : boolean,
  'stopLossPercent' : number,
  'targetPercent' : number,
}
export interface Trade {
  'id' : bigint,
  'pnl' : number,
  'status' : string,
  'userId' : string,
  'mode' : string,
  'side' : string,
  'stopLoss' : number,
  'timestamp' : bigint,
  'quantity' : bigint,
  'price' : number,
  'strategyName' : string,
  'symbol' : string,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addStrategy' : ActorMethod<
    [string, bigint, bigint, number, number, bigint, number, string],
    bigint
  >,
  'addTrade' : ActorMethod<
    [string, string, string, bigint, number, string],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'closeTrade' : ActorMethod<[bigint], undefined>,
  'exitAllTrades' : ActorMethod<[], undefined>,
  'forceAddDailyCandle' : ActorMethod<
    [number, number, number, number, bigint, string, string, bigint],
    undefined
  >,
  'getAdminDashboardStats' : ActorMethod<
    [],
    {
      'activeStrategies' : bigint,
      'todayPnl' : number,
      'squareOffMode' : boolean,
      'accountBalance' : number,
      'activeTrades' : bigint,
      'totalStrategies' : bigint,
      'winRate' : number,
    }
  >,
  'getAdminStats' : ActorMethod<
    [],
    {
      'totalTrades' : bigint,
      'totalPnl' : number,
      'openTrades' : bigint,
      'totalUsers' : bigint,
    }
  >,
  'getAllTrades' : ActorMethod<[], Array<Trade>>,
  'getBrokerConfig' : ActorMethod<[], BrokerConfig>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCandles' : ActorMethod<[string, string, bigint], Array<Candle>>,
  'getMyBacktestResults' : ActorMethod<[], Array<BacktestResult>>,
  'getMyTrades' : ActorMethod<[], Array<Trade>>,
  'getRiskSettings' : ActorMethod<[], RiskSettings>,
  'getSquareOffMode' : ActorMethod<[], boolean>,
  'getStrategies' : ActorMethod<[], Array<Strategy>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'modifyStopLoss' : ActorMethod<[bigint, number], undefined>,
  'saveBacktestResult' : ActorMethod<
    [bigint, string, string, number, number, number, number, bigint],
    bigint
  >,
  'saveBrokerConfig' : ActorMethod<
    [string, string, string, string, string, boolean, boolean, string],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveRiskSettings' : ActorMethod<
    [number, bigint, number, boolean],
    undefined
  >,
  'setTradingMode' : ActorMethod<[string], undefined>,
  'toggleAlgorithm' : ActorMethod<[], undefined>,
  'toggleSquareOffMode' : ActorMethod<[], undefined>,
  'toggleStrategy' : ActorMethod<[bigint], undefined>,
  'updateTrade' : ActorMethod<[bigint, string, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];