/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ApiKey = IDL.Record({
  'id' : IDL.Nat,
  'active' : IDL.Bool,
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'keyHash' : IDL.Text,
});
export const Trade = IDL.Record({
  'id' : IDL.Nat,
  'pnl' : IDL.Float64,
  'status' : IDL.Text,
  'userId' : IDL.Text,
  'mode' : IDL.Text,
  'side' : IDL.Text,
  'stopLoss' : IDL.Float64,
  'timestamp' : IDL.Int,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
  'strategyName' : IDL.Text,
  'symbol' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'experienceLevel' : IDL.Text,
  'country' : IDL.Text,
  'followersCount' : IDL.Nat,
  'name' : IDL.Text,
  'joinedAt' : IDL.Int,
  'role' : IDL.Text,
  'pendingApproval' : IDL.Bool,
  'email' : IDL.Text,
  'tradingMarket' : IDL.Text,
});
export const BrokerConfig = IDL.Record({
  'redirectUrl' : IDL.Text,
  'paperMode' : IDL.Bool,
  'secret' : IDL.Text,
  'webhook' : IDL.Text,
  'algorithmEnabled' : IDL.Bool,
  'apiKey' : IDL.Text,
  'accessToken' : IDL.Text,
  'liveMode' : IDL.Bool,
  'tradingMode' : IDL.Text,
});
export const Candle = IDL.Record({
  'low' : IDL.Float64,
  'timeframe' : IDL.Text,
  'high' : IDL.Float64,
  'close' : IDL.Float64,
  'open' : IDL.Float64,
  'volume' : IDL.Nat,
  'timestamp' : IDL.Int,
  'symbol' : IDL.Text,
});
export const BacktestResult = IDL.Record({
  'id' : IDL.Nat,
  'totalTrades' : IDL.Nat,
  'timeframe' : IDL.Text,
  'userId' : IDL.Text,
  'createdAt' : IDL.Int,
  'sharpeRatio' : IDL.Float64,
  'totalPnl' : IDL.Float64,
  'winRate' : IDL.Float64,
  'maxDrawdown' : IDL.Float64,
  'symbol' : IDL.Text,
  'strategyId' : IDL.Nat,
});
export const NinetwentyState = IDL.Record({
  'line' : IDL.Float64,
  'entry' : IDL.Float64,
  'stopLoss' : IDL.Float64,
  'signal' : IDL.Text,
});
export const RiskSettings = IDL.Record({
  'autoShutdown' : IDL.Bool,
  'maxDailyLoss' : IDL.Float64,
  'maxTradesPerDay' : IDL.Nat,
  'maxCapitalPerTrade' : IDL.Float64,
});
export const Strategy = IDL.Record({
  'id' : IDL.Nat,
  'algorithmFile' : IDL.Text,
  'riskPercent' : IDL.Float64,
  'name' : IDL.Text,
  'shortWindow' : IDL.Nat,
  'longWindow' : IDL.Nat,
  'positionSize' : IDL.Nat,
  'enabled' : IDL.Bool,
  'stopLossPercent' : IDL.Float64,
  'targetPercent' : IDL.Float64,
  'strategyType' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStrategy' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'addTrade' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'approveCreator' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearNinetwentyState' : IDL.Func([], [], []),
  'closeTrade' : IDL.Func([IDL.Nat], [], []),
  'exitAllTrades' : IDL.Func([], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'forceAddDailyCandle' : IDL.Func(
      [
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Int,
      ],
      [],
      [],
    ),
  'generateApiKey' : IDL.Func([IDL.Text], [ApiKey], []),
  'getAdminDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'activeStrategies' : IDL.Nat,
          'todayPnl' : IDL.Float64,
          'squareOffMode' : IDL.Bool,
          'accountBalance' : IDL.Float64,
          'activeTrades' : IDL.Nat,
          'totalStrategies' : IDL.Nat,
          'winRate' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getAdminStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalTrades' : IDL.Nat,
          'totalPnl' : IDL.Float64,
          'openTrades' : IDL.Nat,
          'totalUsers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAllTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getBrokerConfig' : IDL.Func([], [BrokerConfig], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCandles' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Vec(Candle)],
      ['query'],
    ),
  'getMyApiKeys' : IDL.Func([], [IDL.Vec(ApiKey)], ['query']),
  'getMyBacktestResults' : IDL.Func([], [IDL.Vec(BacktestResult)], ['query']),
  'getMyTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
  'getNinetwentyLine' : IDL.Func([], [IDL.Float64], ['query']),
  'getNinetwentyState' : IDL.Func([], [NinetwentyState], ['query']),
  'getPendingCreators' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getRiskSettings' : IDL.Func([], [RiskSettings], ['query']),
  'getSquareOffMode' : IDL.Func([], [IDL.Bool], ['query']),
  'getStrategies' : IDL.Func([], [IDL.Vec(Strategy)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'modifyStopLoss' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
  'rejectCreator' : IDL.Func([IDL.Principal], [], []),
  'revokeApiKey' : IDL.Func([IDL.Nat], [], []),
  'saveBacktestResult' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'saveBrokerConfig' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
      ],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveRiskSettings' : IDL.Func(
      [IDL.Float64, IDL.Nat, IDL.Float64, IDL.Bool],
      [],
      [],
    ),
  'setNinetwentyLine' : IDL.Func([IDL.Float64], [], []),
  'setNinetwentySignal' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'setTradingMode' : IDL.Func([IDL.Text], [], []),
  'toggleAlgorithm' : IDL.Func([], [], []),
  'toggleSquareOffMode' : IDL.Func([], [], []),
  'toggleStrategy' : IDL.Func([IDL.Nat], [], []),
  'updateTrade' : IDL.Func([IDL.Nat, IDL.Text, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ApiKey = IDL.Record({
    'id' : IDL.Nat,
    'active' : IDL.Bool,
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'keyHash' : IDL.Text,
  });
  const Trade = IDL.Record({
    'id' : IDL.Nat,
    'pnl' : IDL.Float64,
    'status' : IDL.Text,
    'userId' : IDL.Text,
    'mode' : IDL.Text,
    'side' : IDL.Text,
    'stopLoss' : IDL.Float64,
    'timestamp' : IDL.Int,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
    'strategyName' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'experienceLevel' : IDL.Text,
    'country' : IDL.Text,
    'followersCount' : IDL.Nat,
    'name' : IDL.Text,
    'joinedAt' : IDL.Int,
    'role' : IDL.Text,
    'pendingApproval' : IDL.Bool,
    'email' : IDL.Text,
    'tradingMarket' : IDL.Text,
  });
  const BrokerConfig = IDL.Record({
    'redirectUrl' : IDL.Text,
    'paperMode' : IDL.Bool,
    'secret' : IDL.Text,
    'webhook' : IDL.Text,
    'algorithmEnabled' : IDL.Bool,
    'apiKey' : IDL.Text,
    'accessToken' : IDL.Text,
    'liveMode' : IDL.Bool,
    'tradingMode' : IDL.Text,
  });
  const Candle = IDL.Record({
    'low' : IDL.Float64,
    'timeframe' : IDL.Text,
    'high' : IDL.Float64,
    'close' : IDL.Float64,
    'open' : IDL.Float64,
    'volume' : IDL.Nat,
    'timestamp' : IDL.Int,
    'symbol' : IDL.Text,
  });
  const BacktestResult = IDL.Record({
    'id' : IDL.Nat,
    'totalTrades' : IDL.Nat,
    'timeframe' : IDL.Text,
    'userId' : IDL.Text,
    'createdAt' : IDL.Int,
    'sharpeRatio' : IDL.Float64,
    'totalPnl' : IDL.Float64,
    'winRate' : IDL.Float64,
    'maxDrawdown' : IDL.Float64,
    'symbol' : IDL.Text,
    'strategyId' : IDL.Nat,
  });
  const NinetwentyState = IDL.Record({
    'line' : IDL.Float64,
    'entry' : IDL.Float64,
    'stopLoss' : IDL.Float64,
    'signal' : IDL.Text,
  });
  const RiskSettings = IDL.Record({
    'autoShutdown' : IDL.Bool,
    'maxDailyLoss' : IDL.Float64,
    'maxTradesPerDay' : IDL.Nat,
    'maxCapitalPerTrade' : IDL.Float64,
  });
  const Strategy = IDL.Record({
    'id' : IDL.Nat,
    'algorithmFile' : IDL.Text,
    'riskPercent' : IDL.Float64,
    'name' : IDL.Text,
    'shortWindow' : IDL.Nat,
    'longWindow' : IDL.Nat,
    'positionSize' : IDL.Nat,
    'enabled' : IDL.Bool,
    'stopLossPercent' : IDL.Float64,
    'targetPercent' : IDL.Float64,
    'strategyType' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStrategy' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addTrade' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'approveCreator' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearNinetwentyState' : IDL.Func([], [], []),
    'closeTrade' : IDL.Func([IDL.Nat], [], []),
    'exitAllTrades' : IDL.Func([], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'forceAddDailyCandle' : IDL.Func(
        [
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Int,
        ],
        [],
        [],
      ),
    'generateApiKey' : IDL.Func([IDL.Text], [ApiKey], []),
    'getAdminDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'activeStrategies' : IDL.Nat,
            'todayPnl' : IDL.Float64,
            'squareOffMode' : IDL.Bool,
            'accountBalance' : IDL.Float64,
            'activeTrades' : IDL.Nat,
            'totalStrategies' : IDL.Nat,
            'winRate' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getAdminStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalTrades' : IDL.Nat,
            'totalPnl' : IDL.Float64,
            'openTrades' : IDL.Nat,
            'totalUsers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAllTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getBrokerConfig' : IDL.Func([], [BrokerConfig], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCandles' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Vec(Candle)],
        ['query'],
      ),
    'getMyApiKeys' : IDL.Func([], [IDL.Vec(ApiKey)], ['query']),
    'getMyBacktestResults' : IDL.Func([], [IDL.Vec(BacktestResult)], ['query']),
    'getMyTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
    'getNinetwentyLine' : IDL.Func([], [IDL.Float64], ['query']),
    'getNinetwentyState' : IDL.Func([], [NinetwentyState], ['query']),
    'getPendingCreators' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getRiskSettings' : IDL.Func([], [RiskSettings], ['query']),
    'getSquareOffMode' : IDL.Func([], [IDL.Bool], ['query']),
    'getStrategies' : IDL.Func([], [IDL.Vec(Strategy)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'modifyStopLoss' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
    'rejectCreator' : IDL.Func([IDL.Principal], [], []),
    'revokeApiKey' : IDL.Func([IDL.Nat], [], []),
    'saveBacktestResult' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'saveBrokerConfig' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
        ],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveRiskSettings' : IDL.Func(
        [IDL.Float64, IDL.Nat, IDL.Float64, IDL.Bool],
        [],
        [],
      ),
    'setNinetwentyLine' : IDL.Func([IDL.Float64], [], []),
    'setNinetwentySignal' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'setTradingMode' : IDL.Func([IDL.Text], [], []),
    'toggleAlgorithm' : IDL.Func([], [], []),
    'toggleSquareOffMode' : IDL.Func([], [], []),
    'toggleStrategy' : IDL.Func([IDL.Nat], [], []),
    'updateTrade' : IDL.Func([IDL.Nat, IDL.Text, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };