/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BrokerConnection {
    broker: string;
    paperMode: boolean;
    secret: string;
    apiKey: string;
    connected: boolean;
    accessToken: string;
}
export interface BacktestResult {
    id: bigint;
    totalTrades: bigint;
    timeframe: string;
    userId: string;
    createdAt: bigint;
    sharpeRatio: number;
    totalPnl: number;
    winRate: number;
    maxDrawdown: number;
    symbol: string;
    strategyId: bigint;
}
export interface RiskSettings {
    autoShutdown: boolean;
    maxDailyLoss: number;
    maxTradesPerDay: bigint;
    maxCapitalPerTrade: number;
}
export interface BrokerConfig {
    redirectUrl: string;
    paperMode: boolean;
    secret: string;
    webhook: string;
    algorithmEnabled: boolean;
    apiKey: string;
    accessToken: string;
    liveMode: boolean;
    tradingMode: string;
}
export interface SubscriptionRecord {
    active: boolean;
    subscribedAt: bigint;
    listingId: bigint;
    userId: string;
    plan: string;
}
export interface Trade {
    id: bigint;
    pnl: number;
    status: string;
    userId: string;
    mode: string;
    side: string;
    stopLoss: number;
    timestamp: bigint;
    quantity: bigint;
    price: number;
    strategyName: string;
    symbol: string;
}
export interface NinetwentyState {
    line: number;
    entry: number;
    stopLoss: number;
    signal: string;
}
export interface ApiKey {
    id: bigint;
    active: boolean;
    userId: string;
    name: string;
    createdAt: bigint;
    keyHash: string;
}
export interface MarketplaceListing {
    id: bigint;
    lifetimePrice: number;
    createdAt: bigint;
    creatorId: string;
    description: string;
    isFree: boolean;
    creatorName: string;
    sharpeRatio: number;
    enabled: boolean;
    subscribers: bigint;
    monthlyPrice: number;
    assetType: string;
    winRate: number;
    strategyName: string;
    maxDrawdown: number;
}
export interface Notification {
    id: bigint;
    userId: string;
    notificationType: string;
    read: boolean;
    message: string;
    emailEnabled: boolean;
    timestamp: bigint;
}
export interface Candle {
    low: number;
    timeframe: string;
    high: number;
    close: number;
    open: number;
    volume: bigint;
    timestamp: bigint;
    symbol: string;
}
export interface ExtendedRiskSettings {
    autoStopTrading: boolean;
    maxOpenTrades: bigint;
    capitalAllocation: number;
    maxTradeRisk: number;
    maxDailyLoss: number;
}
export interface Strategy {
    id: bigint;
    algorithmFile: string;
    riskPercent: number;
    name: string;
    shortWindow: bigint;
    longWindow: bigint;
    positionSize: bigint;
    enabled: boolean;
    stopLossPercent: number;
    targetPercent: number;
    strategyType: string;
}
export interface UserProfile {
    experienceLevel: string;
    country: string;
    followersCount: bigint;
    name: string;
    joinedAt: bigint;
    role: string;
    pendingApproval: boolean;
    email: string;
    tradingMarket: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addNotification(userId: string, notificationType: string, message: string): Promise<Notification>;
    addStrategy(name: string, shortWindow: bigint, longWindow: bigint, stopLossPercent: number, targetPercent: number, positionSize: bigint, riskPercent: number, algorithmFile: string, strategyType: string): Promise<bigint>;
    addTrade(symbol: string, strategyName: string, side: string, quantity: bigint, price: number, mode: string): Promise<bigint>;
    approveCreator(user: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearNinetwentyState(): Promise<void>;
    closeTrade(id: bigint): Promise<void>;
    disconnectBroker(broker: string): Promise<void>;
    exitAllTrades(): Promise<void>;
    followUser(target: Principal): Promise<void>;
    forceAddDailyCandle(open: number, high: number, low: number, close: number, volume: bigint, symbol: string, timeframe: string, timestamp: bigint): Promise<void>;
    generateApiKey(name: string): Promise<ApiKey>;
    getActiveMarketplaceListings(): Promise<Array<MarketplaceListing>>;
    getAdminDashboardStats(): Promise<{
        activeStrategies: bigint;
        todayPnl: number;
        squareOffMode: boolean;
        accountBalance: number;
        activeTrades: bigint;
        totalStrategies: bigint;
        winRate: number;
    }>;
    getAdminStats(): Promise<{
        totalTrades: bigint;
        totalPnl: number;
        openTrades: bigint;
        totalUsers: bigint;
    }>;
    getAllTrades(): Promise<Array<Trade>>;
    getAllUsers(): Promise<Array<[Principal, UserProfile]>>;
    getBrokerConfig(): Promise<BrokerConfig>;
    getBrokerConnections(): Promise<Array<BrokerConnection>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCandles(symbol: string, timeframe: string, limit: bigint): Promise<Array<Candle>>;
    getExtendedRiskSettings(): Promise<ExtendedRiskSettings>;
    getMarketplaceListings(): Promise<Array<MarketplaceListing>>;
    getMyApiKeys(): Promise<Array<ApiKey>>;
    getMyBacktestResults(): Promise<Array<BacktestResult>>;
    getMyNotifications(): Promise<Array<Notification>>;
    getMyTrades(): Promise<Array<Trade>>;
    getNinetwentyLine(): Promise<number>;
    getNinetwentyState(): Promise<NinetwentyState>;
    getNotificationUnreadCount(): Promise<bigint>;
    getPendingCreators(): Promise<Array<[Principal, UserProfile]>>;
    getPublicUserProfile(user: Principal): Promise<UserProfile | null>;
    getRiskSettings(): Promise<RiskSettings>;
    getSquareOffMode(): Promise<boolean>;
    getStrategies(): Promise<Array<Strategy>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserSubscriptions(): Promise<Array<SubscriptionRecord>>;
    isCallerAdmin(): Promise<boolean>;
    markNotificationsRead(): Promise<void>;
    modifyStopLoss(tradeId: bigint, newStopLoss: number): Promise<void>;
    rejectCreator(user: Principal): Promise<void>;
    revokeApiKey(keyId: bigint): Promise<void>;
    saveBacktestResult(strategyId: bigint, symbol: string, timeframe: string, totalPnl: number, winRate: number, maxDrawdown: number, sharpeRatio: number, totalTrades: bigint): Promise<bigint>;
    saveBrokerConfig(apiKey: string, secret: string, accessToken: string, redirectUrl: string, webhook: string, paperMode: boolean, liveMode: boolean, tradingMode: string): Promise<void>;
    saveBrokerConnection(broker: string, apiKey: string, secret: string, accessToken: string, paperMode: boolean): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveExtendedRiskSettings(maxDailyLoss: number, maxTradeRisk: number, maxOpenTrades: bigint, capitalAllocation: number, autoStopTrading: boolean): Promise<void>;
    saveMarketplaceListing(strategyName: string, creatorName: string, description: string, assetType: string, winRate: number, sharpeRatio: number, maxDrawdown: number, monthlyPrice: number, lifetimePrice: number, isFree: boolean): Promise<bigint>;
    saveRiskSettings(maxDailyLoss: number, maxTradesPerDay: bigint, maxCapitalPerTrade: number, autoShutdown: boolean): Promise<void>;
    setNinetwentyLine(line: number): Promise<void>;
    setNinetwentySignal(signal: string, entry: number, stopLoss: number): Promise<void>;
    setTradingMode(mode: string): Promise<void>;
    subscribeToStrategy(listingId: bigint, plan: string): Promise<void>;
    toggleAlgorithm(): Promise<void>;
    toggleSquareOffMode(): Promise<void>;
    toggleStrategy(id: bigint): Promise<void>;
    updateNotificationEmailPref(notificationType: string, emailEnabled: boolean): Promise<void>;
    updateStrategyPricing(listingId: bigint, monthlyPrice: number, lifetimePrice: number, isFree: boolean): Promise<void>;
    updateTrade(id: bigint, status: string, pnl: number): Promise<void>;
}
import type { UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addNotification(arg0: string, arg1: string, arg2: string): Promise<Notification> {
        if (this.processError) {
            try {
                const result = await this.actor.addNotification(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNotification(arg0, arg1, arg2);
            return result;
        }
    }
    async addStrategy(arg0: string, arg1: bigint, arg2: bigint, arg3: number, arg4: number, arg5: bigint, arg6: number, arg7: string, arg8: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addStrategy(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStrategy(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async addTrade(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: number, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrade(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrade(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async approveCreator(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveCreator(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveCreator(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearNinetwentyState(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearNinetwentyState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearNinetwentyState();
            return result;
        }
    }
    async closeTrade(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.closeTrade(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closeTrade(arg0);
            return result;
        }
    }
    async disconnectBroker(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.disconnectBroker(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disconnectBroker(arg0);
            return result;
        }
    }
    async exitAllTrades(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.exitAllTrades();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exitAllTrades();
            return result;
        }
    }
    async followUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0);
            return result;
        }
    }
    async forceAddDailyCandle(arg0: number, arg1: number, arg2: number, arg3: number, arg4: bigint, arg5: string, arg6: string, arg7: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.forceAddDailyCandle(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.forceAddDailyCandle(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async generateApiKey(arg0: string): Promise<ApiKey> {
        if (this.processError) {
            try {
                const result = await this.actor.generateApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateApiKey(arg0);
            return result;
        }
    }
    async getActiveMarketplaceListings(): Promise<Array<MarketplaceListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveMarketplaceListings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveMarketplaceListings();
            return result;
        }
    }
    async getAdminDashboardStats(): Promise<{
        activeStrategies: bigint;
        todayPnl: number;
        squareOffMode: boolean;
        accountBalance: number;
        activeTrades: bigint;
        totalStrategies: bigint;
        winRate: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminDashboardStats();
            return result;
        }
    }
    async getAdminStats(): Promise<{
        totalTrades: bigint;
        totalPnl: number;
        openTrades: bigint;
        totalUsers: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getAllTrades(): Promise<Array<Trade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrades();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrades();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getBrokerConfig(): Promise<BrokerConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getBrokerConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBrokerConfig();
            return result;
        }
    }
    async getBrokerConnections(): Promise<Array<BrokerConnection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBrokerConnections();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBrokerConnections();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCandles(arg0: string, arg1: string, arg2: bigint): Promise<Array<Candle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCandles(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCandles(arg0, arg1, arg2);
            return result;
        }
    }
    async getExtendedRiskSettings(): Promise<ExtendedRiskSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getExtendedRiskSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExtendedRiskSettings();
            return result;
        }
    }
    async getMarketplaceListings(): Promise<Array<MarketplaceListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketplaceListings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketplaceListings();
            return result;
        }
    }
    async getMyApiKeys(): Promise<Array<ApiKey>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyApiKeys();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyApiKeys();
            return result;
        }
    }
    async getMyBacktestResults(): Promise<Array<BacktestResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBacktestResults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBacktestResults();
            return result;
        }
    }
    async getMyNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNotifications();
            return result;
        }
    }
    async getMyTrades(): Promise<Array<Trade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTrades();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTrades();
            return result;
        }
    }
    async getNinetwentyLine(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getNinetwentyLine();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNinetwentyLine();
            return result;
        }
    }
    async getNinetwentyState(): Promise<NinetwentyState> {
        if (this.processError) {
            try {
                const result = await this.actor.getNinetwentyState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNinetwentyState();
            return result;
        }
    }
    async getNotificationUnreadCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotificationUnreadCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotificationUnreadCount();
            return result;
        }
    }
    async getPendingCreators(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingCreators();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingCreators();
            return result;
        }
    }
    async getPublicUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRiskSettings(): Promise<RiskSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getRiskSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRiskSettings();
            return result;
        }
    }
    async getSquareOffMode(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getSquareOffMode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSquareOffMode();
            return result;
        }
    }
    async getStrategies(): Promise<Array<Strategy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStrategies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStrategies();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSubscriptions(): Promise<Array<SubscriptionRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSubscriptions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSubscriptions();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationsRead();
            return result;
        }
    }
    async modifyStopLoss(arg0: bigint, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.modifyStopLoss(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.modifyStopLoss(arg0, arg1);
            return result;
        }
    }
    async rejectCreator(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectCreator(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectCreator(arg0);
            return result;
        }
    }
    async revokeApiKey(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeApiKey(arg0);
            return result;
        }
    }
    async saveBacktestResult(arg0: bigint, arg1: string, arg2: string, arg3: number, arg4: number, arg5: number, arg6: number, arg7: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveBacktestResult(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveBacktestResult(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async saveBrokerConfig(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: boolean, arg6: boolean, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveBrokerConfig(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveBrokerConfig(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async saveBrokerConnection(arg0: string, arg1: string, arg2: string, arg3: string, arg4: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveBrokerConnection(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveBrokerConnection(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveExtendedRiskSettings(arg0: number, arg1: number, arg2: bigint, arg3: number, arg4: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveExtendedRiskSettings(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveExtendedRiskSettings(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async saveMarketplaceListing(arg0: string, arg1: string, arg2: string, arg3: string, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMarketplaceListing(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMarketplaceListing(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async saveRiskSettings(arg0: number, arg1: bigint, arg2: number, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveRiskSettings(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveRiskSettings(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async setNinetwentyLine(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setNinetwentyLine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setNinetwentyLine(arg0);
            return result;
        }
    }
    async setNinetwentySignal(arg0: string, arg1: number, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setNinetwentySignal(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setNinetwentySignal(arg0, arg1, arg2);
            return result;
        }
    }
    async setTradingMode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTradingMode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTradingMode(arg0);
            return result;
        }
    }
    async subscribeToStrategy(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.subscribeToStrategy(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subscribeToStrategy(arg0, arg1);
            return result;
        }
    }
    async toggleAlgorithm(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleAlgorithm();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleAlgorithm();
            return result;
        }
    }
    async toggleSquareOffMode(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleSquareOffMode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleSquareOffMode();
            return result;
        }
    }
    async toggleStrategy(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleStrategy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleStrategy(arg0);
            return result;
        }
    }
    async updateNotificationEmailPref(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNotificationEmailPref(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNotificationEmailPref(arg0, arg1);
            return result;
        }
    }
    async updateStrategyPricing(arg0: bigint, arg1: number, arg2: number, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStrategyPricing(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStrategyPricing(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateTrade(arg0: bigint, arg1: string, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrade(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrade(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
